E2e tests for covering the main functionalities

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -66,6 +66,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -159,6 +160,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -253,6 +255,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -346,6 +349,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -439,6 +443,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -532,6 +537,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -625,6 +631,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -718,6 +725,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -811,6 +819,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -904,6 +913,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -997,6 +1007,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -1090,6 +1101,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -1183,6 +1195,7 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_e2e
+          source tests/testRigor/run_testrigor_tests.sh
         if: ${{ success() || failure() }}
 
       - name: Api testing
@@ -1223,7 +1236,7 @@ jobs:
 
 
   build_nginx_84:
-    name: PHP 8.4 - Nginx - MariaDB 11.4
+    name: PHP 8.4 - Nginx - MariaDB 11.4 (skipping E2e testing at this time)
     runs-on: ubuntu-22.04
     env:
       DOCKER_DIR: nginx_84
@@ -1273,11 +1286,12 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
-      - name: E2e testing
+      - name: E2e testing (skipping at this time for PHP 8.4-dev)
         run: |
-          source ci/ciLibrary.source
-          build_test_e2e
-        if: ${{ success() || failure() }}
+           echo "SKIPPING THIS TEST FOR NOW UNTIL IT STARTS WORKING IN FUTURE FOR PHP 8.4-dev"
+#          source ci/ciLibrary.source
+#          build_test_e2e
+#        if: ${{ success() || failure() }}
 
       - name: Api testing
         run: |
